name: Generate Tag

on:
  push:
    branches:
      - master

jobs:
  genrate-tag:
    name: Generate tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'

      # Generate tag if commit message contains #major or #patch or #patch
      - name: Bump version and push tag
        id: generate_tag
        uses: ChloePlanet/github-tag-action@master
        env:
          # An action in a workflow run can't trigger a new workflow run.
          # When you use secrets.GITHUB_TOKEN in your actions, all of the interactions 
          # with the repository are on behalf of the github-actions bot. 
          # The operations act by github-actions bot cannot trigger a new workflow run.
          # So use GitHub Personal Access Token in GITHUB_TOKEN 
          # if you want to trigger another workflow by this workflow.
          # 
          # More details: 
          # https://help.github.com/en/actions/reference/events-that-trigger-workflows#about-workflow-events
          # https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          WITH_V: true

      # Generate changelog for new major or minor version.
      - name: Generate changelog
        if: steps.generate_tag.outputs.tag_generated == 1 && (steps.generate_tag.outputs.bump_ver == 'major' || steps.generate_tag.outputs.bump_ver == 'minor')
        uses: docker://ferrarimarco/github-changelog-generator:latest
        with:
          # TODO: Replace user and project flag with your own info
          args: -u ChloePlanet -p repo-template --output ${{ format('CHANGELOG/CHANGELOG-{0}.{1}.md', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }} --header-label="${{ format('# CHANGELOG-{0}.{1}', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }}" --since-tag=${{ steps.generate_tag.outputs.last_tag }} --no-unreleased
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Rewrite changelog for new patch version.
      - name: Set since tag
        if: steps.generate_tag.outputs.tag_generated == 1 && steps.generate_tag.outputs.bump_ver == 'patch'
        run: echo ::set-env name=since_tag::$(git describe --tags --abbrev=0 ${{ format('v{0}.{1}.0^', steps.generate_tag.outputs.last_major, steps.generate_tag.outputs.last_minor) }})

      - name: Rewrite changelog
        if: env.since_tag != ''
        uses: docker://ferrarimarco/github-changelog-generator:latest
        with:
          # TODO: Replace user and project flag with your own info
          args: -u ChloePlanet -p repo-template --output ${{ format('CHANGELOG/CHANGELOG-{0}.{1}.md', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }} --header-label="${{ format('# CHANGELOG-{0}.{1}', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }}" --since-tag=${{ env.since_tag }} --no-unreleased
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        if: steps.generate_tag.outputs.tag_generated == 1
        # TODO: Replace the user email and name
        run: |
          git config --local user.email "changelog@bot.com"
          git config --local user.name "ChangelogBot"
          git add .
          git commit -m "docs: generate ${{ format('CHANGELOG/CHANGELOG-{0}.{1}.md', steps.generate_tag.outputs.major, steps.generate_tag.outputs.minor) }}" && echo ::set-env name=can_push::1 || echo "No changes to CHANGELOG"

      - name: Push changes
        if: env.can_push == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
